# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9b288480202a4dea13f6440d4560028db9a40d64e8806e6cff6d5bde46905cf936908a3a0269a9bced58ebd7a082495ebbdb40969b362faecb6915e0beed1052

test:
  secret_key_base: 4a0389703bab8a99d2e44bd6ff020bf9041c2f42e149755ba90654fde94f7f9c4ef0674c55e0ffd9f5f895bbe8bdc88063f0a7e1cba8c2c7c57e1eb42815f810

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
